### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by proydu** [rochi88/bdshare#2]
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

 × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9acher1p/bdshare_548cd89fc4094f6b8529e85e116222a6/setup.py", line 8, in <module>
          with open('CHANGELOG.md') as history_file:
      FileNotFoundError: [Errno 2] No such file or directory: 'CHANGELOG.md'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.

**Comment by rochi88** [comment]
fixed on [2d76972](https://github.com/rochi88/bdshare/commit/2d7697272e44421a2fb23aa185f8e17b2a81c0a9)
